package software.amazon.awssdk.enhanced.dynamodb.extensions.annotations;

import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGenerateStrategy;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampAttributeTags;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.BeanTableSchemaAttributeTag;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * DynamoDB Enhanced Annotation which mimics the functionality provided by annotation @DynamoDBAutoGeneratedTimestamp
 * in the DynamoDB Mapper within SDK 1.11
 *
 * Supports both strategies ALWAYS and CREATE.
 * ALWAYS - Add timestamp on create and update (Default)
 * CREATE - Only add timestamp on update
 *
 * Ex.
 *
 * private Instant lastUpdatedTimestamp;
 *
 * @DynamoDbAutoGeneratedTimestampAttribute(strategy = AutoGenerateStrategy.ALWAYS)
 * public Instant getLastUpdatedTimestamp() {
 *     return this.lastUpdatedTimestamp;
 * }
 *
 */
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@BeanTableSchemaAttributeTag(AutoGeneratedTimestampAttributeTags.class)
public @interface DynamoDbAutoGeneratedTimestampAttribute {

    AutoGenerateStrategy strategy() default AutoGenerateStrategy.ALWAYS;
}
