package software.amazon.awssdk.enhanced.dynamodb.extensions;

import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.StaticAttributeTag;

public class AutoGeneratedTimestampAttributeTags {
    private AutoGeneratedTimestampAttributeTags() {
    }

    public static StaticAttributeTag attributeTagFor(final DynamoDbAutoGeneratedTimestampAttribute annotation) {
        return AutoGeneratedTimestampExtension.AttributeTags.autoGeneratedTimestamp(annotation.strategy());
    }
}